let products=[];
const catNames={rodas:'Rodas & acessórios',pneus:'Pneus',motor:'Motor',suspensao:'Suspensão',cubos:'Cubos de roda'};
let cart=[];try{const saved=JSON.parse(localStorage.getItem('lp_cart')||'[]');cart=Array.isArray(saved)?saved.filter(i=>i&&typeof i.id==='string'&&Number.isFinite(i.qty)&&i.qty>0):[]}catch(_){localStorage.removeItem('lp_cart')}
let currentFilter='all';
const brl=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function render(){const search=document.getElementById('search'),root=document.getElementById('catalog');if(!root)return;const q=(search?.value||'').toLowerCase();const cats=currentFilter==='all'?Object.keys(catNames):[currentFilter];const html=cats.map(cat=>{const ps=products.filter(p=>p.cat===cat&&(!q||JSON.stringify(p).toLowerCase().includes(q)));if(!ps.length)return '';return `<section class="category" id="${cat}"><div class="category-head"><div><div class="eyebrow">${catNames[cat]}</div><h2>${cat==='pneus'?'Escolha a medida e o modelo':'Produtos selecionados'}</h2></div><small>${ps.length} produtos nesta categoria</small></div><div class="products">${ps.map(card).join('')}</div></section>`}).join('');root.innerHTML=html||'<div class="empty">Nenhum produto encontrado.</div>';updateCount()}
function card(p){return `<article class="card"><div class="photo">${p.img?`<img src="${p.img}" alt="${p.name}" loading="lazy" onerror="this.parentElement.classList.add('image-error')">`:'<div class="no-photo">Imagem do produto</div>'}</div><div class="card-body"><span class="tag">${p.tag}</span><h3>${p.name}</h3><div class="code">Código/ref.: ${p.code}</div><p class="desc">${p.desc}</p><div class="price">${brl(p.price)}</div><div class="pix">PIX: ${brl(p.pix)}</div><div class="stock">Preço de referência pesquisado • confirme estoque e condição antes da venda.</div><div class="actions"><button class="buy" onclick="add('${p.id}')">Comprar no site</button><button class="talk" onclick="talk('${p.id}')">Especialista</button></div></div></article>`}
function add(id){const p=products.find(x=>x.id===id);if(!p)return;const x=cart.find(i=>i.id===id);if(x)x.qty++;else cart.push({id,qty:1});save();openCart()}
function save(){localStorage.setItem('lp_cart',JSON.stringify(cart));updateCount()}
function updateCount(){const el=document.getElementById('cartCount');if(el)el.textContent=cart.reduce((a,b)=>a+b.qty,0)}
function openCart(){renderCart();document.getElementById('cartModal').classList.add('open')}
function closeCart(){document.getElementById('cartModal').classList.remove('open')}
function renderCart(){const el=document.getElementById('cartItems');if(!cart.length){el.innerHTML='<div class="empty">Seu carrinho está vazio.</div>';document.getElementById('cartTotal').textContent=brl(0);return}let total=0;el.innerHTML=cart.map(i=>{const p=products.find(x=>x.id===i.id);if(!p)return '';total+=p.price*i.qty;return `<div class="cart-row"><img src="${p.img||''}" onerror="this.style.visibility='hidden'"><div><strong>${p.name}</strong><small>${brl(p.pix)} no PIX</small></div><div class="qty"><button onclick="changeQty('${p.id}',-1)">−</button><span>${i.qty}</span><button onclick="changeQty('${p.id}',1)">+</button></div></div>`}).join('');document.getElementById('cartTotal').textContent=brl(total)}
function changeQty(id,d){const x=cart.find(i=>i.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(i=>i.id!==id);save();renderCart()}
function buildWhatsappMessage(items,total,name){const lines=items.map(i=>{const p=products.find(x=>x.id===i.id);return p?`• ${p.name} | Código/ref.: ${p.code} | Qtd.: ${i.qty} | ${brl(p.pix)} cada`:''}).filter(Boolean).join('\n');return `Olá! Tentei finalizar minha compra pelo site Linha Pesada, mas o PIX não foi gerado.\n\nGostaria de finalizar a compra diretamente com o especialista.\n\n${name?`Nome: ${name}\n`:''}Produtos:\n${lines}\n\nValor total no PIX: ${brl(total)}\n\nPode me atender e finalizar esse pedido, por favor?`}
function openWhatsappCheckout(items,total,name){const msg=encodeURIComponent(buildWhatsappMessage(items,total,name));window.open(`https://api.whatsapp.com/send/?phone=5512981160171&text=${msg}&type=phone_number&app_absent=0`,'_blank')}
function talk(id){const p=products.find(x=>x.id===id);if(!p)return;const msg=encodeURIComponent(`Olá! Vim pelo site e quero comprar: ${p.name}. Código/ref.: ${p.code}. Pode confirmar aplicação, estoque e condição?`);window.open(`https://api.whatsapp.com/send/?phone=5512981160171&text=${msg}&type=phone_number&app_absent=0`,'_blank')}
function checkout(){if(!cart.length)return;closeCart();const total=cart.reduce((s,i)=>s+(products.find(p=>p.id===i.id)?.pix||0)*i.qty,0);document.getElementById('checkoutContent').innerHTML=`<div class="eyebrow">CHECKOUT PIX</div><h2>Finalize sua compra</h2><p style="color:#91a1ae;font-size:12px">Preencha os dados do pagador. O site enviará a solicitação ao seu backend, que por sua vez chama a API da GGPIXAPI.</p><div class="form-grid"><input id="buyerName" placeholder="Nome completo"><input id="buyerEmail" placeholder="E-mail"><input id="buyerDoc" placeholder="CPF ou CNPJ"><input id="buyerPhone" placeholder="Telefone"><input id="buyerAddress" class="full" placeholder="Endereço para entrega"></div><div class="pay-note">Total do pedido: <strong>${brl(total)}</strong>. O valor enviado ao gateway será em centavos.</div><button class="checkout" onclick="createPix(${total})">Gerar PIX e pagar</button>`;document.getElementById('checkoutModal').classList.add('open')}
function closeCheckout(){document.getElementById('checkoutModal').classList.remove('open')}
function apiError(data,status){if(!data)return `Falha ao criar cobrança (HTTP ${status})`;const candidates=[data.error,data.message,data.detail,data.description,data.reason,data.error_description,data.errors?.message,data.errors?.detail];const found=candidates.find(v=>typeof v==='string'&&v.trim());if(found)return `${found} (HTTP ${status})`;if(data.errors&&typeof data.errors==='object')return `${JSON.stringify(data.errors)} (HTTP ${status})`;const keys=Object.keys(data);if(keys.length)return `${JSON.stringify(data)} (HTTP ${status})`;return `Falha ao criar cobrança (HTTP ${status})`}
async function createPix(total){const name=document.getElementById('buyerName').value.trim(),email=document.getElementById('buyerEmail').value.trim(),doc=document.getElementById('buyerDoc').value.replace(/\D/g,''),phone=document.getElementById('buyerPhone').value.trim(),address=document.getElementById('buyerAddress').value.trim();if(!name||!/^([0-9]{11}|[0-9]{14})$/.test(doc)){alert('Informe nome e CPF/CNPJ válido.');return}const checkoutItems=cart.map(i=>({id:i.id,qty:i.qty}));const payload={amountCents:Math.round(total*100),payerName:name,payerDocument:doc,payerEmail:email,payerPhone:phone,metadata:{items:cart,source:'site-linha-pesada',address}};const box=document.getElementById('checkoutContent');try{const r=await fetch('/api/create-pix',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(payload)});const raw=await r.text();let data={};try{data=raw?JSON.parse(raw):{}}catch(_){throw new Error(`O servidor retornou uma resposta inválida (HTTP ${r.status}).`)}if(!r.ok)throw new Error(apiError(data,r.status));const pix=data.pixCopyPaste||data.pixCode||data.brCode;if(!pix)throw new Error('A API criou a cobrança, mas não retornou o código PIX Copia e Cola.');const qr=data.qrCode||data.qrCodeImage;box.innerHTML=`<div class="eyebrow">PIX GERADO</div><h2>Agora é só pagar</h2><p style="color:#91a1ae;font-size:12px">A cobrança foi criada. Aguarde a confirmação do pagamento antes de considerar o pedido concluído.</p>${qr?`<div class="pix-qr"><img src="${qr}" alt="QR Code PIX"></div>`:''}<div class="pix-box"><strong>PIX Copia e Cola</strong><div class="pix-code" id="pixCode">${pix}</div><button class="copy" onclick="navigator.clipboard.writeText(document.getElementById('pixCode').innerText);this.textContent='Copiado!'">Copiar código PIX</button></div>`;cart=[];save()}catch(e){box.innerHTML=`<div class="eyebrow">PIX INDISPONÍVEL</div><h2>Vamos finalizar sua compra</h2><p style="color:#91a1ae;font-size:13px">Não foi possível gerar o PIX para este pedido agora. Você pode finalizar a compra diretamente com nosso especialista pelo WhatsApp.</p><div class="pay-note"><strong>Valor do pedido: ${brl(total)}</strong><br>Os produtos e o valor já serão enviados na mensagem.</div><button class="checkout" onclick='openWhatsappCheckout(${JSON.stringify(checkoutItems)},${total},${JSON.stringify(name)})'>Finalizar pelo WhatsApp</button><div class="pay-note" style="margin-top:10px;color:#91a1ae;font-size:11px">Se preferir, você também pode fechar esta janela e tentar novamente.</div>`}}
async function init(){try{const r=await fetch('/products.json?catalog=20260904',{cache:'no-store'});if(!r.ok)throw new Error(`Catálogo indisponível (HTTP ${r.status})`);const data=await r.json();if(!Array.isArray(data)||data.length!==50)throw new Error('Catálogo incompleto');products=data;render()}catch(e){const root=document.getElementById('catalog');if(root)root.innerHTML=`<div class="empty">Não foi possível carregar o catálogo agora. ${e.message}</div>`;console.error(e)}}
document.querySelectorAll('.filter').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');currentFilter=b.dataset.filter;render()}));document.getElementById('search').addEventListener('input',render);updateCount();init();