(function(){
  const WA_URL='https://api.whatsapp.com/send/?phone=5512981160171&text=Ol%C3%A1%21%20Vim%20pelo%20site%20e%20quero%20ajuda%20com%20uma%20pe%C3%A7a.&type=phone_number&app_absent=0';
  function replaceTop(){
    const topbar=document.querySelector('.topbar'),header=document.querySelector('header.header'),mainnav=document.querySelector('.mainnav'),hero=document.querySelector('section.hero');
    if(!topbar||!header||!mainnav||!hero)return;
    topbar.innerHTML=`<div class="manus-wrap manus-topbar-in"><div class="manus-top-left"><span>▣ &nbsp;<b>CNPJ: 09.284.909/0001-93</b></span><span>♟ &nbsp;Loja especializada em peças para caminhões</span></div><div class="manus-top-right"><span>⬟ &nbsp;Compra segura</span><a href="${WA_URL}" target="_blank" rel="noopener">◉ &nbsp;Atendimento via WhatsApp</a></div></div>`;
    header.innerHTML=`<div class="manus-wrap manus-header-in"><a class="manus-brand" href="#top" aria-label="Linha Pesada"><img src="/assets/logo-linha-pesada.svg" alt="Linha Pesada — peças e acessórios para caminhões"></a><div class="manus-search"><input id="manusTopSearch" placeholder="O que você está procurando?" autocomplete="off"><button type="button" aria-label="Buscar" id="manusSearchBtn">⌕</button></div><div class="manus-contact"><a class="manus-wa-contact" href="${WA_URL}" target="_blank" rel="noopener"><span class="manus-wa-circle">◉</span><span><b>Fale conosco</b><small>Atendimento via WhatsApp</small></span></a><span class="manus-divider"></span><span class="manus-location"><span class="manus-loc-icon">⌖</span><span><b>Guanambi/BA</b><small>Atendimento nacional</small></span></span><button class="manus-cart" type="button" onclick="openCart()">🛒 <span>Carrinho</span> <b id="manusCartCount">0</b></button></div></div>`;
    mainnav.innerHTML=`<div class="manus-wrap manus-nav-in"><a class="active" href="#top">Início</a><a href="#rodas">Rodas</a><a href="#pneus">Pneus</a></div>`;
    hero.innerHTML=`<div class="manus-hero-bg"><img src="/manus-top-hero.webp" alt="Caminhões Pesados - Linha Pesada"><div class="manus-hero-overlay"></div></div><div class="manus-wrap manus-hero-in"><div class="manus-hero-copy"><span class="manus-hero-eyebrow">PEÇAS E ACESSÓRIOS PARA</span><h1>CAMINHÕES</h1><p>Qualidade, segurança e o melhor preço para manter o seu trabalho em movimento.</p><div class="manus-hero-benefits"><div><span>◆</span><b>Produtos com garantia comprovada</b></div><div><span>✓</span><b>Compra segura e entrega rápida</b></div><div><span>◉</span><b>Atendimento especializado</b></div></div></div><div class="manus-discount"><strong>20%</strong><b>DE DESCONTO</b><small>EM TODA A LOJA</small></div></div>`;
    const category=document.querySelector('.category-showcase');
    if(category){
      category.innerHTML=`<div class="manus-category-wrap"><div class="manus-category-head"><h2>NAVEGUE PELAS CATEGORIAS PRINCIPAIS</h2><span>Totalmente focado em 25 Pneus e 25 Rodas Reais</span></div><div class="manus-category-grid"><a class="manus-category-card" href="#pneus"><div class="manus-category-copy"><span class="manus-category-badge">25 Produtos Cadastrados</span><h3>Pneus</h3><p>Pneus pesados radiais, mistos e para linha 3/4 de marcas reais como Michelin, Bridgestone, Goodyear, Continental, Pirelli, Dunlop, Westlake e outras.</p><div class="manus-category-link">Veja todos os preços <b>›</b></div></div><div class="manus-category-image"><img src="/produto-imagem/p1" alt="Pneus" onerror="this.onerror=null;this.src='/assets/cat-pneus-ref.jpg'"></div></a><a class="manus-category-card" href="#rodas"><div class="manus-category-copy"><span class="manus-category-badge">25 Produtos Cadastrados</span><h3>Rodas</h3><p>Rodas de alumínio forjado alto brilho e rodas de aço de alta resistência nos aros 22.5, 17.5 e 20 para todas as aplicações de carga.</p><div class="manus-category-link">Veja todos os preços <b>›</b></div></div><div class="manus-category-image"><img src="/assets/cat-rodas-ref.jpg" alt="Rodas"></div></a></div></div>`;
    }
    const topSearch=document.getElementById('manusTopSearch'),oldSearch=document.getElementById('search');
    const syncSearch=()=>{if(!oldSearch||!topSearch)return;oldSearch.value=topSearch.value;oldSearch.dispatchEvent(new Event('input',{bubbles:true}));};
    topSearch.addEventListener('input',syncSearch);document.getElementById('manusSearchBtn')?.addEventListener('click',()=>{syncSearch();document.getElementById('produtos')?.scrollIntoView({behavior:'smooth'});});
    const cartCount=document.getElementById('cartCount'),manusCartCount=document.getElementById('manusCartCount');const syncCart=()=>{if(cartCount&&manusCartCount)manusCartCount.textContent=cartCount.textContent||'0';};syncCart();if(cartCount)new MutationObserver(syncCart).observe(cartCount,{childList:true,characterData:true,subtree:true});
  }
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',replaceTop);else replaceTop();
})();
